[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "meilisearch>=0.34.1",
    "textract==1.6.3",
    "uvicorn>=0.34.2",
]
